name: "Deployment Workflow"
on: 
    push:
        branches:
            - tests


jobs: 
    simple_deploy:
        runs-on: ubuntu-latest
        steps:
        - name: "Checkouts out"
          uses: actions/checkout@v4

        - name: "Print the Github object"
          run: |
              echo "APP_VERSION=${RANDOM}" >> $GITHUB_ENV

        - name: "Build the image"
          run: |
                echo ${{ env.APP_VERSION }}
       
                sudo docker build -t theoafactor/bik_latest:${{ env.APP_VERSION }} frontend/

        - name: "Login to Docker Hub"
          uses: docker/login-action@v3
          with: 
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
            
        - name: "Push the image to DockerHub"
          run: |
                docker push theoafactor/bik_latest:${{ env.APP_VERSION }}

        - name: "Announce the latest version of the deployment"
          uses: dawidd6/action-send-mail@v3
          with:
            username: theoafactor@gmail.com
            password: ${{ secrets.EMAIL_PASSWORD }}
            server_address: smtp.gmail.com
            server_port: 465
            secure: true
            subject: "New Docker Image Version for Simple Web App"
            to: "theoafactor@gmail.com"
            from: Olu Adeyemo <theoafactor@gmail.com>
            body: "New image build: ${{ env.APP_VERSION }}"


            

